import { Case, Conversation, TeamMember, Interaction } from './types';

export const MOCK_CASES: Case[] = [
  {
    id: 'SADA-89422-QX',
    clientName: 'Alpha Meridan',
    tier: 'Tier 1 Strategic',
    lastInteraction: '2 hours ago',
    value: 1420000,
    growth: '+4.2% Growth',
    status: 'OPEN',
    riskProfile: 'Moderate',
    exposure: 142500,
    slaCountdown: '04:12:55',
  },
  {
    id: 'KL-10293',
    clientName: 'Kaelo Logistics',
    tier: 'Standard Mid-Market',
    lastInteraction: 'Yesterday, 4:30 PM',
    value: 890200,
    growth: 'Stable',
    status: 'PENDING',
    riskProfile: 'Low',
    exposure: 45000,
    slaCountdown: '12:00:00',
  },
  {
    id: 'VT-55210',
    clientName: 'VantEdge Tech',
    tier: 'New Acquisition',
    lastInteraction: '3 days ago',
    value: 2105400,
    growth: '+0.8% Growth',
    status: 'RESOLVED',
    riskProfile: 'Low',
    exposure: 0,
    slaCountdown: '00:00:00',
  },
  {
    id: 'SN-99281',
    clientName: 'Stellar Networks',
    tier: 'Tier 1 Strategic',
    lastInteraction: '4 hours ago',
    value: 540300,
    growth: 'At Risk',
    status: 'PENDING',
    riskProfile: 'High',
    exposure: 540300,
    slaCountdown: '01:45:10',
  },
  {
    id: 'NX-11223',
    clientName: 'Nexus Corp',
    tier: 'Tier 1 Strategic',
    lastInteraction: '1 hour ago',
    value: 3200000,
    growth: '+12.5% Growth',
    status: 'OPEN',
    riskProfile: 'Low',
    exposure: 100000,
    slaCountdown: '08:00:00',
  },
  {
    id: 'OR-44556',
    clientName: 'Orbit Systems',
    tier: 'Standard Mid-Market',
    lastInteraction: '5 hours ago',
    value: 750000,
    growth: '-2.1% Decline',
    status: 'OPEN',
    riskProfile: 'Moderate',
    exposure: 150000,
    slaCountdown: '02:30:00',
  },
  {
    id: 'PX-77889',
    clientName: 'Pulse Dynamics',
    tier: 'New Acquisition',
    lastInteraction: 'Yesterday',
    value: 1200000,
    growth: '+5.0% Growth',
    status: 'PENDING',
    riskProfile: 'Moderate',
    exposure: 300000,
    slaCountdown: '10:15:00',
  },
  {
    id: 'QX-99001',
    clientName: 'Quantum Leap',
    tier: 'Tier 1 Strategic',
    lastInteraction: '2 days ago',
    value: 4500000,
    growth: 'Stable',
    status: 'RESOLVED',
    riskProfile: 'Low',
    exposure: 0,
    slaCountdown: '00:00:00',
  },
  {
    id: 'RX-22334',
    clientName: 'Rift Solutions',
    tier: 'Standard Mid-Market',
    lastInteraction: '6 hours ago',
    value: 600000,
    growth: 'At Risk',
    status: 'OPEN',
    riskProfile: 'High',
    exposure: 600000,
    slaCountdown: '00:45:00',
  },
  {
    id: 'SX-55667',
    clientName: 'Solaris Energy',
    tier: 'Tier 1 Strategic',
    lastInteraction: '3 hours ago',
    value: 2800000,
    growth: '+3.2% Growth',
    status: 'OPEN',
    riskProfile: 'Low',
    exposure: 50000,
    slaCountdown: '05:20:00',
  },
  {
    id: 'TX-88990',
    clientName: 'Terraform Inc',
    tier: 'New Acquisition',
    lastInteraction: '4 days ago',
    value: 950000,
    growth: 'Stable',
    status: 'PENDING',
    riskProfile: 'Moderate',
    exposure: 200000,
    slaCountdown: '15:00:00',
  },
  {
    id: 'UX-11224',
    clientName: 'Unity Global',
    tier: 'Standard Mid-Market',
    lastInteraction: '7 hours ago',
    value: 1100000,
    growth: '+1.5% Growth',
    status: 'RESOLVED',
    riskProfile: 'Low',
    exposure: 0,
    slaCountdown: '00:00:00',
  },
  {
    id: 'VX-44557',
    clientName: 'Vortex Media',
    tier: 'Tier 1 Strategic',
    lastInteraction: '8 hours ago',
    value: 5200000,
    growth: '+8.4% Growth',
    status: 'OPEN',
    riskProfile: 'Moderate',
    exposure: 400000,
    slaCountdown: '03:10:00',
  },
  {
    id: 'WX-77890',
    clientName: 'Waveform Labs',
    tier: 'New Acquisition',
    lastInteraction: 'Yesterday',
    value: 1500000,
    growth: '-1.0% Decline',
    status: 'PENDING',
    riskProfile: 'High',
    exposure: 1500000,
    slaCountdown: '01:20:00',
  },
  {
    id: 'XX-99002',
    clientName: 'Xenon Tech',
    tier: 'Standard Mid-Market',
    lastInteraction: '9 hours ago',
    value: 800000,
    growth: 'Stable',
    status: 'OPEN',
    riskProfile: 'Low',
    exposure: 20000,
    slaCountdown: '06:45:00',
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: '1',
    participant: 'Marcus Chen',
    participantRole: 'ENTERPRISE GOLD',
    lastMessage: "The portfolio rebalancing for Q3 hasn't reflected in my dashboard yet.",
    timestamp: '14:20',
    status: 'active',
    priority: false,
    channel: 'Email',
    avatar: 'https://picsum.photos/seed/marcus/100/100',
  },
  {
    id: '2',
    participant: 'Elena Rodriguez',
    participantRole: 'VIP CLIENT',
    lastMessage: "I'm looking at the SMS verification code, but it says expired.",
    timestamp: 'Now',
    status: 'active',
    priority: true,
    channel: 'SMS',
    avatar: 'https://picsum.photos/seed/elena/100/100',
    typing: true,
  },
  {
    id: '3',
    participant: 'David Sterling',
    participantRole: 'ASSET MANAGEMENT',
    lastMessage: 'Missed call. Voice note transcribed: "Need to discuss the risk assessment..."',
    timestamp: '11:05',
    status: 'active',
    priority: false,
    channel: 'Voice',
    avatar: 'https://picsum.photos/seed/david/100/100',
  },
];

export const MOCK_INTERACTIONS: Interaction[] = [
  {
    id: 'i1',
    type: 'Outgoing Call Attempt',
    description: 'Contact successful. Client requested payment plan deferral for Q4 invoice.',
    timestamp: '10:45 AM Today',
    agent: 'Agent Sarah',
  },
  {
    id: 'i2',
    type: 'Auto-Generated SMS Sent',
    description: 'Payment reminder link sent via Twilio Gateway (ID: TX-902).',
    timestamp: 'Yesterday, 4:20 PM',
  },
  {
    id: 'i3',
    type: 'Case Opened',
    description: 'Delinquency threshold breached. System auto-assigned to SADA High Priority queue.',
    timestamp: 'Oct 24, 09:15 AM',
  },
];

export const MOCK_TEAM: TeamMember[] = [
  {
    id: 't1',
    name: 'Sarah Jenkins',
    role: 'SENIOR AGENT',
    avatar: 'https://picsum.photos/seed/sarah/100/100',
    resolved: 342,
    rating: 4.9,
    sla: 98,
    goalProgress: 88,
    status: 'online',
    focus: [
      { name: 'Enterprise API Audit', color: 'bg-blue-500' },
      { name: 'Q3 Retrospective', color: 'bg-orange-500' },
    ],
    trend: [10, 25, 15, 30, 20, 45, 40],
  },
  {
    id: 't2',
    name: 'Marcus Thorne',
    role: 'PORTFOLIO MANAGER',
    avatar: 'https://picsum.photos/seed/marcus2/100/100',
    resolved: 215,
    rating: 4.7,
    sla: 92,
    goalProgress: 74,
    status: 'offline',
    focus: [
      { name: 'Tier 1 Migration', color: 'bg-red-500' },
      { name: 'Contract Renewal', color: 'bg-blue-500' },
    ],
    trend: [20, 15, 25, 20, 25, 20, 20],
  },
  {
    id: 't3',
    name: 'Elena Rodriguez',
    role: 'SENIOR AGENT',
    avatar: 'https://picsum.photos/seed/elena2/100/100',
    resolved: 412,
    rating: 5.0,
    sla: 100,
    goalProgress: 96,
    status: 'online',
    focus: [
      { name: 'VIP Account Onboarding', color: 'bg-green-500' },
      { name: 'Knowledge Base Update', color: 'bg-blue-500' },
    ],
    trend: [15, 20, 35, 30, 40, 35, 50],
  },
];
